In [1]:
import pandas as pd
import numpy as np

In [14]:
x = np.random.randint(0,100, (10,4))

In [15]:
x

array([[85, 45,  5, 68],
       [22,  6, 69, 79],
       [36, 79,  1, 66],
       [76, 27, 51, 26],
       [32, 70, 65, 82],
       [92, 38, 37, 69],
       [54, 20, 13, 42],
       [67, 29, 77, 67],
       [52, 35,  3, 49],
       [22, 34, 93,  1]])

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_x = scaler.fit_transform(x)
scaler.scale_, scaler.mean_, scaler.var_

(array([24.32611765, 20.80408614, 32.55518392, 24.28353352]),
 array([53.8, 38.3, 41.4, 54.9]),
 array([ 591.76,  432.81, 1059.84,  589.69]))

In [18]:
scaled_x

array([[ 1.28257211,  0.32205212, -1.1181015 ,  0.53946021],
       [-1.30723696, -1.55257961,  0.84779125,  0.99244206],
       [-0.73172383,  1.95634645, -1.2409698 ,  0.45709987],
       [ 0.91259938, -0.54316253,  0.29488391, -1.19010687],
       [-0.89615615,  1.52373912,  0.72492295,  1.11598256],
       [ 1.57032867, -0.01442024, -0.13515513,  0.58064037],
       [ 0.00822162, -0.87963489, -0.87236491, -0.53122417],
       [ 0.54262666, -0.44702757,  1.09352784,  0.49828004],
       [-0.07399454, -0.15862268, -1.17953565, -0.24296299],
       [-1.30723696, -0.20669017,  1.58500103, -2.21961108]])

In [19]:
scaled_x.mean()

6.661338147750939e-17

In [22]:
scaled_x.mean(axis=0)

array([1.11022302e-16, 1.33226763e-16, 4.44089210e-17, 4.44089210e-17])

In [23]:
scaled_x.std(axis=0)

array([1., 1., 1., 1.])

In [24]:
from sklearn.preprocessing import OneHotEncoder
roles = np.array([('Tom', 'manager'),
                 ('Mary', 'developer'),
                 ('Ann', 'recruiter'),
                 ('Jim', 'developer')])
roles

array([['Tom', 'manager'],
       ['Mary', 'developer'],
       ['Ann', 'recruiter'],
       ['Jim', 'developer']], dtype='<U9')

In [31]:
encoder = OneHotEncoder()
encoder_roles = encoder.fit_transform(roles[:,[1]])
encoder_roles.toarray()

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [29]:
roles[:,[1]]

array([['manager'],
       ['developer'],
       ['recruiter'],
       ['developer']], dtype='<U9')

In [57]:
from sklearn.model_selection import train_test_split
Y = x[:,[3]]
X = x[:,[0,1,2]]
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=0)

In [59]:
x_test

array([[36, 79,  1],
       [52, 35,  3],
       [32, 70, 65],
       [22, 34, 93]])

In [66]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=10, random_state=0)
regressor.fit(x_train, y_train.ravel())

RandomForestRegressor(n_estimators=10, random_state=0)

In [67]:
regressor.score(x_train, y_train)

0.6961563195646798

In [68]:
regressor.score(x_test, y_test)

-0.20638685139907653

In [64]:
y_train.ravel()

array([79, 42, 67, 26, 68, 69])

Бостонские квартиры

In [69]:
from sklearn.datasets import load_wine
x, y = load_wine(return_X_y=True)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)

In [70]:
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [71]:
regressor.score(x_train, y_train)

0.9820077355836849

In [73]:
regressor.score(x_test, y_test)

0.913235294117647

In [79]:
regressor.predict([[1.376e+01, 1.510e+00, 2.630e+00, 1.500e+01, 8.600e+01, 2.950e+00,
        2.860e+00, 2.100e-01, 1.850e+00, 3.380e+00, 4.360e+00, 2.160e+00,
        4.100e+02]])

array([0.9])